// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookCaféRest.model
{
    [Table("Book")]
    public partial class Book
    {
        [Key]
        [StringLength(50)]
        public string Author { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [Required]
        [StringLength(50)]
        public string Genre { get; set; }
        [Required]
        [StringLength(50)]
        public string Publisher { get; set; }
        [Required]
        [StringLength(50)]
        public string Description { get; set; }
        public int Price { get; set; }
    }
}